REDFIN_FIELDS = [
    'Location id',
    'url',
    'Price',
    '# of Covered Spaces',
    '# of Floors In Building',
    '# of Floors/Stories (Total)',
    '# of Garage Spaces',
    '# of Parcels',
    '# of Parking Spaces',
    '# of Stalls',
    '# of Stories',
    '# of Times Leased/Year Allowed',
    '# of Units',
    '# of Units In Building',
    'APN',
    'Accessibility Features',
    'Accessible',
    'Acres',
    'Active Date',
    'Additional Furnished Info',
    'Additional Water Information',
    'Adjusted Gross Sq. Ft',
    'Appliances',
    'Assessment Information',
    'Assessment Information_Total Assessed Value',
    'Assessor Information_Assessment Year',
    'Assessor Information_Tax District County',
    'Assessor Information_Year of Last Land Appraisal',
    'Association Amenities',
    'Association Deposit Amount',
    'Association Email',
    'Association Fee',
    'Association Fee 2',
    'Association Fee Frequency',
    'Association Fee Includes',
    'Association Phone',
    'Association URL',
    'Available Documents_Available Documents',
    'Available Information',
    'Basement',
    'Bathroom Information',
    'Bathroom Information_# of Bathroom Fixtures',
    'Bathroom Information_# of Baths (1/2)',
    'Bathroom Information_# of Baths (Full)',
    'Bathroom Information_# of Baths (Half)',
    'Bathroom Information_# of Baths (Total)',
    'Bathroom Information_# of Full Baths',
    'Bathroom Information_Main Level Bathrooms',
    'Baths',
    'Bedroom Information',
    'Bedroom Information_# of Bedrooms',
    'Bedroom Information_Bedroom Description',
    'Bedroom Information_Main Level Bedrooms',
    'Beds',
    'Boat Services Information',
    'Boat Services Information_Dock',
    'Branded Virtual Tour_Branded Virtual Tour',
    'Builder Name',
    'Building Construction Quality',
    'Building Improvement Type',
    'Building Information',
    'Building Information_# of Floors',
    'Building Information_# of Units',
    'Building Information_Amenities',
    'Building Information_Building Features',
    'Building Information_Construction',
    'Building Information_Construction Details',
    'Building Information_Construction Materials',
    'Building Information_Construction Type',
    'Building Information_Development Name',
    'Building Information_Exterior Wall',
    'Building Information_Housing Older Persons Act',
    'Building Information_Roof',
    'Building Information_Roof Details',
    'Building Information_Stories',
    'Building Information_Stories (Total)',
    'Building Information_Storm Protection Impact Glass',
    'Building Information_Structure',
    'Building Information_Total # of Floors',
    'Building Information_Total # of Units',
    'Building Information_Year Built',
    'Building Sq. Ft',
    'Building Style Type',
    'Building Type',
    'Buyer Details',
    'Carport Spaces',
    'Community Features',
    'Community Information',
    'Community Information_Association Amenities',
    'Community Information_Association Fee Includes',
    'Community Information_Community Features',
    'Condo Fee',
    'Condo Fee Frequency',
    'Condo Security',
    'Construction',
    'Construction Details',
    'Construction Materials',
    'Construction Quality (1-Lowest, 10-Highest)',
    'Construction Type',
    'Cooling Information_Cooling Type',
    'County',
    'County Use Description',
    'Depth Footage',
    'Development Name',
    'Development Status',
    'Dining Area Information',
    'Dining Room Dimensions',
    'Dining Room Information_Dining Area Dimensions',
    'Dining Room Information_Dining Description',
    'Dining Room Information_Dining Room Dimensions',
    'Direction Faces',
    'Disaster Mitigation',
    'Documents & Disclosures_Affidavit YN',
    'Documents & Disclosures_Disclosures',
    'Entry Level',
    'Entry Location',
    'Equestrian Features',
    'Equestrian Features_# of Barns',
    'Equipment',
    'Equipment_Appliances',
    'Existing Lease Tenant YN',
    'Expenses Information',
    'Expenses Information_Total Expenses',
    'Exterior Features',
    'Exterior Features_Exterior Features',
    'Exterior Features_Fencing',
    'Exterior Features_Other Structures',
    'Exterior Features_Patio And Porch Features',
    'Exterior Features_Security Features',
    'Exterior Information',
    'Exterior Information_Building Construction Quality',
    'Exterior Information_Building Style Type',
    'Exterior Information_Construction Type',
    'Exterior Information_Exterior Material',
    'Exterior Information_Exterior Wall',
    'Exterior Information_Floor Construction Type',
    'Exterior Information_Foundation Type',
    'Exterior Information_Patio Balcony Dimensions',
    'Exterior Information_Phyiscal Condition',
    'Exterior Information_Roof Type',
    'Exterior Wall',
    'Features',
    'Fencing Information',
    'Financial Information_CDD Fee',
    'Finished Sq. Ft.',
    'Fire District',
    'Fireplace Information',
    'Fireplace Information_# of Fireplaces',
    'Fireplace Information_Fireplace Features',
    'Floor Description',
    'Floor Number',
    'Flooring',
    'Flooring Information',
    'Flooring Information_Flooring',
    'Foundation Information_Foundation Type',
    'Foundation Type',
    'Front Exposure',
    'Front Footage',
    'Front Property Width',
    'Frontage Length',
    'Furnished',
    'Furnished Info',
    'Furnished Information',
    'Garage',
    'Garage / Carport Type',
    'Garage Dimensions',
    'Garage/Carport Information',
    'Garage/Carport Information_# of Carport Spaces',
    'Garage/Carport Information_# of Garage Spaces',
    'General Zoning Class',
    'Governing Body',
    'Green Energy Generation',
    'Green Features_Green Building Verification Type',
    'Green Features_Green Energy Efficient',
    'Green Features_Green Energy Generation',
    'Green Features_Green Indoor Air Quality',
    'Green Features_Green Landscaping',
    'Green Features_Green Water Conservation',
    'Green Features_HERS Index',
    'Green Indoor Air Quality',
    'Green Landscaping',
    'Green Water Conservation',
    'Gross Operating Income',
    'Gross Sq. Ft',
    'Ground Floor Sq. Ft',
    'Guest House Description',
    'Guest House Information',
    'Guest House Information_Sq. Ft.',
    'HERS Index',
    'HOA Dues',
    'HOA Information',
    'HOA Information_Association Fee',
    'HOA Information_Association Fee Includes',
    'Heated Sq. Ft. (Approximate)',
    'Heating',
    'Heating & Cooling',
    'Heating & Cooling_Air Conditioning Type',
    'Heating & Cooling_Cooling',
    'Heating & Cooling_Heating',
    'Heating & Cooling_Heating Fuel Type',
    'Heating & Cooling_Heating Type',
    'Heating Description',
    'Heating Type',
    'Heating and Cooling_Type of Cooling',
    'Heating and Cooling_Type of Heating',
    'High School',
    'Homeowners Association Information',
    'Homeowners Association Information_Amenities Additional Fees',
    'Homeowners Association Information_Application Fee',
    'Homeowners Association Information_Assoc Fee Paid',
    'Homeowners Association Information_Association Fee',
    'Homeowners Association Information_Association Fee Frequency',
    'Homeowners Association Information_Association Name',
    'Homeowners Association Information_Condo Fee Frequency',
    'Homeowners Association Information_Condo Management',
    'Homeowners Association Information_Condo Restrictions',
    'Homeowners Association Information_HOA Fees/Month',
    'Homeowners Association Information_HOA/POA/COA',
    'Homeowners Association Information_Included Fees',
    'Homeowners Association Information_Maintenance Includes',
    'Homeowners Association Information_Membership Equity',
    'Homeowners Association Information_Membership Equity ',
    'Homeowners Association Information_Membership Equity Maximum',
    'Homeowners Association Information_Membership Equity Minimum',
    'Homeowners Association Information_Monthly HOA Amount',
    'Homeowners Association Information_Monthly Maintenance Charge',
    'Homeowners Association Information_Total Annual Fees',
    'Housing Older Persons Act',
    'Included Fees',
    'Income Information_Gross Rent Income',
    'Income Information_Net Operating Income',
    'Interior Features',
    'Interior Features_Accessibility Features',
    'Interior Features_Appliances',
    'Interior Features_Door Features',
    'Interior Features_Flooring',
    'Interior Features_Interior Features',
    'Interior Features_Laundry Features',
    'Interior Features_Other Features',
    'Interior Features_Window Features',
    'Interior Information_# of Ceiling Fans',
    'Interior Information_Equipment Appliances',
    'Interior Information_Floor Description',
    'Kitchen Information',
    'Land Information',
    'Land Information_Acreage',
    'Land Information_Approximate Lot Size',
    'Land Information_Ground Cover',
    'Land Information_Horse Amenities',
    'Land Information_Lot Size Acres',
    'Land Information_Road Frontage',
    'Land Information_Road Surface',
    'Land Information_Roads',
    'Land Information_Vegetation',
    'Land Lease Information_# of Times Leased/Year Allowed',
    'Land Lease Information_Land Lease',
    'Land Lease Information_Land Lease Amount',
    'Land Lease Information_Land Lease Amount Frequency',
    'Land Lease Information_Minimum Days to Lease',
    'Land Lease Information_Recreation Lease',
    'Land Use Code',
    'Laundry Appliances Included',
    'Laundry Features',
    'Laundry Information_Features',
    'Lease Ends',
    'Lease Ends Info',
    'Lease Information_Minimum Num of Days for Lease',
    'Leasing Information',
    'Leasing Information_Additional Lease Restrictions',
    'Leasing Information_Existing Lease Tenant YN',
    'Leasing Information_Minimum Lease',
    'Leasing Information_Num Of Own Years Prior To Lse',
    'Legal Block Number',
    'Legal Description',
    'Legal Lot Number',
    'Listing Date Information',
    'Listing Date Information_Go Active Date',
    'Listing Date Information_Off Market Date',
    'Listing Information',
    'Listing Information_DXORIGMLNO',
    'Listing Information_DXORIGMLSID',
    'Listing Information_Possession Information',
    'Listing Information_Web Address',
    'Location Information',
    'Location Information_Building Number',
    'Location Information_Complex Name',
    'Location Information_Development Name',
    'Location Information_Directions',
    'Location Information_Front Exposure',
    'Location Information_Parcel Location Influence',
    'Location Information_Subdivision Complex Building',
    'Location Information_Subdivision Information',
    'Location Information_Subdivision Number',
    'Lot Depth',
    'Lot Dimensions (Approximate)',
    'Lot Features',
    'Lot Information',
    'Lot Information_# of Buildings',
    'Lot Information_Dimensions',
    'Lot Information_Land Sq. Ft',
    'Lot Information_Legal Lot Number',
    'Lot Information_Lot',
    'Lot Information_Lot Description',
    'Lot Information_Lot Dimensions',
    'Lot Information_Lot Dimensions (Approximate)',
    'Lot Information_Lot Features',
    'Lot Information_Lot Frontage',
    'Lot Information_Lot Location',
    'Lot Information_Lot Size (Sq. Ft.)',
    'Lot Information_Lot Size Acres',
    'Lot Information_Lot Size Area',
    'Lot Information_Municipality Name',
    'Lot Information_Other Structures',
    'Lot Information_Primary Lot Number',
    'Lot Information_Road Frontage Type',
    'Lot Information_Waterfront Features',
    'Lot Information_Waterfront Feet Total',
    'Lot Location',
    'Lot Size',
    'Main Level Bathrooms',
    'Main Living Area',
    'Maintenance Fee Includes',
    'Maintenance Includes',
    'Max Pet Weight Allowed',
    'Membership Equity',
    'Membership Equity Maximum',
    'Membership Equity Minimum',
    'Minimum Lease',
    'Miscellaneous Information',
    'Miscellaneous Information_Maximum Number of Pets',
    'Miscellaneous Information_Pet Fee',
    'Mobile Home Information',
    'Mobile Home Information_Model',
    'Mobile Home Information_Size',
    'Model Name',
    'Monthly HOA Amount',
    'Monthly Income',
    'Monthly Maintenance Charge',
    'Monthly Rent',
    'Montly Maintenance Amount in Addition To HOA Fees',
    'Multi Unit Information_# Of Units In Community',
    'Multi Unit Information_Pets Allowed',
    'Multi-Unit Information',
    'Multi-Unit Information_# of Units in Building (Total)',
    'Multi-Unit Information_# of Units in Complex',
    'Multi-Unit Information_Governing Body',
    'Multi-Unit Information_Net Operating Income',
    'Multi-Unit Information_Restrictions',
    'Multi-Unit Information_Tenant Pays',
    'Multi-Unit Information_Unit Floor #',
    'Municipality Name',
    'Neighborhood Information_Subdivision Name',
    'Num Of Own Years Prior To Lse',
    'Num Times per Year',
    'Open Parking Spaces',
    'Other Features',
    'Other Fee Frequency',
    'Other Pet Restrictions',
    'Other Structures',
    'Parcel Number',
    'Parking',
    'Parking & Garage',
    'Parking & Garage Information_Garage/Parking Sq. Ft',
    'Parking & Garage Information_Parking Type',
    'Parking & Garage_Carport Spaces',
    'Parking & Garage_Garage Spaces',
    'Parking & Garage_Parking Features',
    'Parking Description',
    'Parking Information',
    'Parking Information_# Parking Spaces',
    'Parking Information_# of Carport Spaces',
    'Parking Information_# of Covered Spaces',
    'Parking Information_# of Garage Spaces',
    'Parking Information_Carport Description',
    'Parking Information_Garage Description',
    'Parking Information_Parking Description',
    'Parking Information_Parking Facilities',
    'Parking Information_Parking Restrictions',
    'Parking Restrictions',
    'Parking Spaces',
    'Parking_# of Covered Spaces',
    'Parking_Features',
    'Permit Number',
    'Permitted Remodel Year',
    'Pet Information_Maximum Number Of Pets Allowed',
    'Pet Information_Other Pet Restrictions',
    'Pet Information_Pets Allowed',
    'Pet Restrictions',
    'Pet Size Restriction',
    'Pool Dimensions',
    'Pool Information',
    'Pool Information_Pool',
    'Pool Information_Pool Dimensions',
    'Pool Information_Pool Features',
    'Pool Information_Pool Type',
    'Pool/Spa Information',
    'Pool/Spa Information_Pool Features',
    'Porch/Patio/Balcony',
    'Possession',
    'Presently Zoned',
    'Property Condition',
    'Property Description',
    'Property Information',
    'Property Information_Adjusted Gross Sq. Ft',
    'Property Information_Age of Roof',
    'Property Information_Building Sq. Ft',
    'Property Information_Development Status',
    'Property Information_Direction Faces',
    'Property Information_Entry Level',
    'Property Information_Entry Location',
    'Property Information_Foundation Details',
    'Property Information_Front Exposure',
    'Property Information_Legal Description',
    'Property Information_Living Area',
    'Property Information_Living Area Units',
    'Property Information_Living Sq. Ft',
    'Property Information_Minimum Living Sq. Ft. Restriction',
    'Property Information_Model Name',
    'Property Information_Parcel Number',
    'Property Information_Pet Restrictions',
    'Property Information_Property Legal Description',
    'Property Information_Property Type',
    'Property Information_Sq. Ft.',
    'Property Information_Sq. Ft. (Guest House)',
    'Property Information_Sq. Ft. (Total)',
    'Property Information_Subdivision Name',
    'Property Information_Total number of Stories',
    'Property Information_Zoning Description',
    'Property Sq Ft',
    'Property Sub Type',
    'Property Type',
    'Property Type Information',
    'Rental Information_Currency Monthly Rent Amount',
    'Rental Information_Rent Includes',
    'Rental Information_Required Days of Notice To Tenant If Not Renewed',
    'Restrictions',
    'Road Frontage Type',
    'Road Responsibility',
    'Road Surface Type',
    'Roads',
    'Roof',
    'Roof Covering Type',
    'Roof Description',
    'Roof Details',
    'Roof Framing Type',
    'Roof Shape Type',
    'Roof Type',
    'Room 1 Information',
    'Room 1 Information_Dimensions',
    'Room 1 Information_Room Dimension',
    'Room 10 Information',
    'Room 10 Information_Dimensions',
    'Room 10 Information_Room Dimension',
    'Room 11 Information',
    'Room 11 Information_Dimensions',
    'Room 11 Information_Room Dimension',
    'Room 12 Information',
    'Room 12 Information_Room Dimension',
    'Room 2 Information',
    'Room 2 Information_Dimensions',
    'Room 2 Information_Room Dimension',
    'Room 3 Information',
    'Room 3 Information_Dimensions',
    'Room 3 Information_Room Dimension',
    'Room 4 Information',
    'Room 4 Information_Dimensions',
    'Room 4 Information_Room Dimension',
    'Room 5 Information',
    'Room 5 Information_Dimensions',
    'Room 5 Information_Room Dimension',
    'Room 6 Information',
    'Room 6 Information_Dimensions',
    'Room 6 Information_Room Dimension',
    'Room 7 Information',
    'Room 7 Information_Dimensions',
    'Room 7 Information_Room Dimension',
    'Room 8 Information',
    'Room 8 Information_Dimensions',
    'Room 8 Information_Room Dimension',
    'Room 9 Information',
    'Room 9 Information_Dimensions',
    'Room 9 Information_Room Dimension',
    'Room Description',
    'Room Information',
    'Room Information_# of Rooms',
    'Room Information_# of Rooms (Total)',
    'Room Information_Additional Rooms',
    'Room Information_Dining Area Description',
    'Room Information_Room Count',
    'Room Information_Rooms Description',
    'School Information_Elementary School',
    'School Information_High School',
    'School Information_Junior High School',
    'School Information_Middle Or Junior School',
    'School Information_Middle School',
    'School Information_Senior High School',
    'School_Elementary School',
    'School_Middle Or Junior School',
    'Security Features',
    'Security Information',
    'Security System',
    'Senior High School',
    'Sewer',
    'Sewer Description',
    'Source of Expenses',
    'Spa Features',
    'Special Information',
    'Sprinkler Description',
    'Sq. Ft.',
    'Sq. Ft. (Total)',
    'State Use Description',
    'Stories',
    'Stories Type',
    'Storm Protection',
    'Structure',
    'Structure (Builder)',
    'Style',
    'Subdivision',
    'Subdivision Complex Building',
    'Subdivision Information',
    'Subdivision Number',
    'Tax Information',
    'Tax Information_Annual Amount',
    'Tax Information_Annual Tax Amount',
    'Tax Information_Annual Taxes',
    'Tax Information_Tax Amount',
    'Tax Information_Tax Year',
    'Tax Year',
    'Taxes',
    'Total Annual Fees',
    'Total Assessor Sq. Ft. of Buildings',
    'Total Operating Expenses',
    'Total Sq. Ft.',
    'Total Sq. Ft. of All Structures',
    'Trees',
    'Type of Governing Bodies',
    'Unfinished Sq. Ft.',
    'Unit 1 Information_# of Baths (Full)',
    'Unit 1 Information_# of Bedrooms',
    'Unit 1 Information_# of Units',
    'Unit 1 Information_Equipment',
    'Unit 1 Information_Furniture Info',
    'Unit 2 Information_# of Bathrooms (Full)',
    'Unit 2 Information_# of Baths (Full)',
    'Unit 2 Information_# of Bedrooms',
    'Unit 2 Information_Furniture Info',
    'Unit 3 Information_# of Bathrooms (Full)',
    'Unit 3 Information_# of Baths (Full)',
    'Unit 3 Information_# of Bedrooms',
    'Unit 3 Information_Furniture Info',
    'Unit 3 Information_Monthly Rent',
    'Unit 3 Information_Sq. Ft.',
    'Unit 4 Information_# of Bathrooms (Full)',
    'Unit 4 Information_# of Baths (Full)',
    'Unit 4 Information_# of Bedrooms',
    'Unit 4 Information_Furniture Info',
    'Unit 4 Information_Monthly Rent',
    'Unit 4 Information_Sq. Ft.',
    'Unit Design',
    'Unit Floor #',
    'Unit Floor Location',
    'Unit Information_# of Units',
    'Unit Information_Unit Number',
    'Unit Layout',
    'Unit Location',
    'Utilities Information',
    'Utilities Information_Cooling Description',
    'Utilities Information_Energy Features',
    'Utilities Information_Heating Description',
    'Utilities Information_Utilities',
    'Utility Information',
    'Utility Information_Electric',
    'Utility Information_On-Site Utilities',
    'Utility Information_Sewer',
    'Utility Information_Utilities',
    'Utility Information_Water Source',
    'Utility Room Dimension',
    'Vegetation',
    'View',
    'View Information_View',
    'Virtual Tour',
    'Virtual Tour (External Link)',
    'Water Access',
    'Water Access Type',
    'Water Body Name',
    'Water Description',
    'Water Extras Details',
    'Water Frontage (Ft.)',
    'Water Frontage Feet Lake',
    'Water Frontage Feet Pond',
    'Water Heater',
    'Water Source',
    'Water View',
    'Waterfront Description',
    'Waterfront Features',
    'Waterfront Feet Total',
    'Waterfront Frontage',
    'Waterfront Information',
    'Waterfront Information_Additional Water Information',
    'Waterfront Information_Water Access Type',
    'Waterfront Information_Waterfront Features',
    'Window Features',
    'Window Information',
    'Window Information_Window Treatments',
    'Windows Treatment',
    'Year Built',
    'Year Built Description',
    'Year Built Details',
    'Year Renovated',
    'Year Roof Installed',
    'Zoning Code',
    'Zoning Description',
    'Zoning Information',
]
