REDFIN_KEY_MAP = {
    '# of Bathroom Fixtures': 'Bathroom Information_# of Bathroom Fixtures',
    '# of Bathrooms (Full)': 'Bathroom Information_# of Baths (Full)',
    '# of Bathrooms (Half)': 'Bathroom Information_# of Baths (Half)',
    '# of Baths (1/2)': 'Bathroom Information_# of Baths (Half)',
    '# of Bedrooms': 'Bedroom Information_# of Bedrooms',
    '# of Carport Spaces': 'Garage/Carport Information_# of Carport Spaces',
    'Bathroom Information_# of 1/2 Baths': 'Bathroom Information_# of Baths (Half)',
    'Bathroom Information_# of Full Bathrooms': 'Bathroom Information_# of Baths (Full)',
    'Bathroom Information_# of Half Bathrooms': 'Bathroom Information_# of Baths (Half)',
    'Boat Services Information_Dock Number': 'Boat Services Information_Dock',
    'Building Information_# of Stories': 'Building Information_# of Floors',
    'Building Information_# of Floors/Stories (Total)': 'Building Information_# of Floors',
    'Building Information_# of Units (Total)': 'Building Information_# of Units',
    'Building Information_Year Built Details': 'Building Information_Year Built',
    'Condo Fees': 'Condo Fee',
    'Dock': 'Boat Services Information_Dock',
    'Garage Spaces': 'Garage/Carport Information_# of Garage Spaces',
    'Green Features_Green Energy Efficient Features': 'Green Features_Green Energy Efficient',
}
